# if this is being installed as part of am AMI build we need to clean up
# to allow registration to take place correctly later:
# https://support.jumpcloud.com/customer/portal/articles/2399081-deploying-the-jumpcloud-agent-using-a-template-or-system-image

- name: stop jumpcloud agent for image build clean up
  service:
    name: jcagent
    state: stopped
  become: yes

- name: cleanup config files for image build - {{ item }}
  file:
    path: "{{ item }}"
    state: 'absent'
  with_items:
    - '/opt/jc/ca.crt'
    - '/opt/jc/client.crt'
    - '/opt/jc/client.key'
    - '/opt/jc/jcagent.conf'
  become: yes
