---

- include: install.yml
  when: jumpcloud_install

- include: tag.yml
  when: jumpcloud_tag

- include: cleanup.yml
  when: jumpcloud_image_build

- include: deregister.yml
  when: jumpcloud_shutdown_cleanup
